### ISSUE TITLE
fix: breadcrumbs - ui not included

### ISSUE THREAD

**Issue by dargmuesli** [harlan-zw/nuxt-seo-ui#2]
### Describe the bug

Making use of `useBreadcrumbsUi` does not lead to the defined tailwind classes being included into the existing ([@nuxtjs/tailwindcss](https://tailwindcss.nuxtjs.org/)) stylesheet as expected.

![image](https://github.com/harlan-zw/nuxt-seo-ui/assets/4778485/5d05eba5-3040-46ef-a0c5-a3acf60e7cfc)

Here, only the classes that I use somewhere else in my app are applied, not all, that's why the separators are not positioned correctly.

---

I'd love to know how to implement this correctly, I really want to make use of the same styling in `@dargmuesli/nuxt-cookie-control` :heart_eyes:

**Comment by harlan-zw** [comment]
Hm, the classes should be picked up as the tailwind config is merged within the hook. I just pushed a fix up if you have `config.content` as a string of arrays though.

```ts
 nuxt.hooks.hook('tailwindcss:config', (config) => {
      if (Array.isArray(config.content)) {
        // add our components for scanning
        config.content.push(resolve('./runtime/components/*.vue'))
        config.content.push(resolve('./runtime/composables/useBreadcrumbsUi.ts'))
      }
      else if (config.content?.files && Array.isArray(config.content?.files)) {
        // add our components for scanning
        config.content.files.push(resolve('./runtime/components/*.vue'))
        config.content.files.push(resolve('./runtime/composables/useBreadcrumbsUi.ts'))
      }
    })
```

Maybe you can see if that fixed it for you :thinking:

**Comment by dargmuesli** [comment]
LGTM! Thank you :)
